/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package se.sinetiq.core.demo.application.provider.api;

import se.sinetiq.core.demo.application.provider.model.Units;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-06-20T08:44:02.600773+02:00[Europe/Stockholm]")
@Validated
@Tag(name = "units", description = "the units API")
public interface UnitsApi {
    /**
     * GET /units : Get supported temperature units
     *
     * @return List of supported temperature units (status code 200)
     */
    @Operation(
        operationId = "unitsGet",
        summary = "Get supported temperature units",
        responses = {
            @ApiResponse(responseCode = "200", description = "List of supported temperature units", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Units.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/units",
        produces = { "application/json" }
    )
    ResponseEntity<Units> unitsGet();
}
